version: "3.8"
services:
  web:
    container_name: go-users-app
    build: ./
    ports:
      - "8081:8081"
    command: /app
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: go-users-app-db
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app