version: "3.8"
services:
  app:
    container_name: go-users-app
    build:
      context: .
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    env_file:
      - ./cmd/users/.env
  db:
    container_name: go-users-app-db
    image: postgres:14.1-alpine
    env_file:
      - ./cmd/users/.env
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}